- name: "{{ hashicorp_tool }} : download HashiCorp GPG key"
  become: true
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/etc/apt/trusted.gpg.d/hashicorp.asc"
    checksum: "sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029"

- name: "{{ hashicorp_tool }} : install HashiCorp apt repo"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: "hashicorp"
    state: "present"

- name: "{{ hashicorp_tool }} : install specific package version"
  become: true
  ansible.builtin.apt:
    name: "{{ hashicorp_tool }}={{ hashicorp_tool_version }}-{{ hashicorp_tool_pkg_version }}"
    state: "present"
    update_cache: true
  when: hashicorp_tool_version | length > 0

- name: "{{ hashicorp_tool }} : install latest package version"
  become: true
  ansible.builtin.apt:
    name: "{{ hashicorp_tool }}"
    state: "present"
    update_cache: true
  when: hashicorp_tool_version | length == 0
