hostname: "helios64"

install_docker: false

consul_data_dir: "/data/consul"

nomad_data_dir: "/data/nomad/data"
nomad_datacenter: "dc1"
nomad_node_pool: "storage"
nomad_client_host_volumes:
  - name: "pihole"
    path: "/data/nomad/volumes/pihole"
  - name: "loki"
    path: "/data/nomad/volumes/loki"
  - name: "grafana"
    path: "/data/nomad/volumes/grafana"
  - name: "adguard-conf"
    path: "/data/nomad/volumes/adguard-conf"
  - name: "adguard-work"
    path: "/data/nomad/volumes/adguard-work"
  - name: "home-assistant"
    path: "/data/nomad/volumes/home-assistant"
  - name: "tailscale"
    path: "/data/nomad/volumes/tailscale"
nomad_extra_config_files:
  - src: "{{ playbook_dir }}/templates/99_docker_privileged.hcl"
    dest: "99_docker_privileged.hcl"
