- name: Clone repo
  git:
    repo: https://github.com/pi-hole/pi-hole.git
    dest: /tmp/pihole
    version: "{{ pihole_version }}"

- name: Execute install script
  shell:
    cmd: "./basic-install.sh --unattended"
    chdir: "/tmp/pihole/automated install"

- name: Set web password
  command: pihole -a -p "{{ pihole_web_password }}"

- name: Remove repo
  file:
    path: /tmp/pihole/
    state: absent
