- name: Create config dir
  file:
    path: /etc/pihole
    state: directory

- name: Render config file
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    mode: "0644"
  notify: "Restart DNS"

- name: Render local routes
  template:
    src: custom.list.j2
    dest: /etc/pihole/custom.list
    mode: "0644"
  notify: "Restart DNS"
