- name: "daemon reload"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: "restart systemd-resolved"
  become: true
  ansible.builtin.service:
    name: "systemd-resolved.service"
    state: "restarted"
