- hosts: "servers"
  vars_files:
    - "./vars/secrets.yml"
  roles:
    - role: "common"
      vars:
        common_dns_primary:
          - "8.8.8.8"
          - "9.9.9.9"
      tags: ["common"]

    - role: "nomad"
      vars:
        nomad_version: "1.10.5"
        nomad_agent_name: "{{ inventory_hostname }}"
        nomad_advertise_addr: "{{ ansible_default_ipv4.address }}"
        nomad_server_enabled: true
        nomad_server_server_join: "{{ groups['feijuca_servers'] | map('extract', hostvars, ['ansible_host']) }}"
        nomad_server_bootstrap_expect: "{{ nomad_server_server_join | length }}"
        nomad_server_encrypt_key: "{{ secret_nomad_encrypt_key }}"
        nomad_tls_enabled: false
        nomad_consul_use_ssl: false
      tags: ["tool", "nomad"]
