- hosts: "clients"
  vars_files:
    - "./vars/secrets.yml"
  roles:
    - role: "common"
      vars:
        common_dns_primary:
          - "8.8.8.8"
          - "9.9.9.9"
      tags: ["common"]

    - role: "geerlingguy.docker"
      become: true
      when: "install_docker"
      tags: ["runtime", "docker"]

    - role: "cni_plugins"

    - role: "nomad"
      vars:
        nomad_version: "1.10.5"
        nomad_agent_name: "{{ hostname }}"
        nomad_client_enabled: true
        nomad_client_server_join: "{{ groups['feijuca_servers'] | map('extract', hostvars, ['ansible_host']) }}"
        nomad_tls_enabled: false
        nomad_consul_use_ssl: false
        nomad_extra_config_files:
          - src: "{{ playbook_dir }}/templates/99_docker_privileged.hcl"
            dest: "99_docker_privileged.hcl"
      tags: ["tool", "nomad"]
