- hosts: "servers"
  vars_files:
    - "./vars/secrets.yml"
  roles:
    - role: "common"
    - role: "nomad"
      vars:
        nomad_version: "1.4.2"
        nomad_agent_name: "{{ hostname }}"
        nomad_server_enabled: true
        nomad_server_encrypt_key: "{{ secret_nomad_encrypt_key }}"
        nomad_tls_ca_cert: "{{ lookup('file', './secrets/tls/nomad/nomad-ca.pem') }}"
        nomad_tls_cert: "{{ lookup('file', './secrets/tls/nomad/' + nomad_region + '-server.pem') }}"
        nomad_tls_cert_key: "{{ lookup('file', './secrets/tls/nomad/' + nomad_region + '-server-key.pem') }}"
        nomad_consul_ca_cert: "{{ lookup('file', './secrets/tls/consul/consul-agent-ca.pem') }}"
        nomad_consul_cert: "{{ lookup('file', './secrets/tls/consul/' + consul_datacenter + '-nomad-consul-0.pem') }}"
        nomad_consul_cert_key: "{{ lookup('file', './secrets/tls/consul/' + consul_datacenter + '-nomad-consul-0-key.pem') }}"
        nomad_consul_tags:
          - "traefik.enable=true"
          - "traefik.http.routers.nomad.rule=Host(`nomad.feijuca.fun`)"
      tags: ["tool", "nomad"]
    - role: "consul"
      vars:
        consul_version: "1.13.3"
        consul_node_name: "{{ hostname }}"
        consul_client_addr: "0.0.0.0"
        consul_server_enabled: true
        consul_server_encrypt_key: "{{ secret_consul_encrypt_key }}"
        consul_tls_ca_cert: "{{ lookup('file', './secrets/tls/consul/consul-agent-ca.pem') }}"
        consul_tls_cert: "{{ lookup('file', './secrets/tls/consul/' + consul_datacenter + '-server-consul-0.pem') }}"
        consul_tls_key: "{{ lookup('file', './secrets/tls/consul/' + consul_datacenter + '-server-consul-0-key.pem') }}"
        consul_acl_tokens:
          default: "{{ secret_consul_acl_node_token }}"
      tags: ["tool", "consul"]
